include $(GOROOT)/src/Make.inc

TARG=github.com/wernerd/GoRTP/rtp
GOFILES= \
	doc.go \
	packets.go \
	session.go \
	stream.go \
	payload.go \
	transport.go \
	transportUDP.go

include $(GOROOT)/src/Make.pkg
