include $(GOROOT)/src/Make.inc

TARG=net/rtp
GOFILES= \
    doc.go \
	packets.go \
	session.go \
    stream.go \
    payload.go \
	transport.go \
	transportUDP.go

include $(GOROOT)/src/Make.pkg
